spring.datasource.url=jdbc:postgresql://localhost:5432/lab_resourse_db
spring.datasource.username=postgres
spring.datasource.password=postgres123

# Use 'update' to auto-add missing columns
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Don't run schema.sql automatically - run it manually
spring.sql.init.mode=never

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.springframework.web=DEBUG



#Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=zahiqibrahim51@gmail.com
spring.mail.password=yblqlqqjrushtola
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true



app.email.from=zahiqibrahim51@gmail.com

# OTP Configuration
otp.expiration.minutes=5

#JWT Configuration

jwt.secret=Kag6Swn1LY70OkV3qYM00sDVQaqopGlroMsKoJpDAr6

#30 days
jwt.expiration=2592000000


